### PR TITLE
MultipleChoiceSelection.h: added missing header

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Ditto.

### CODE REVIEW

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
code checks

This should return, I hope

**Comment by knoepfel** [comment]
@PetrilloAtWork, please run the `format-code` command on your changed file (it alphabetizes the headers).

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
+1

**Pull request merged**
