### PR TITLE
Updating Rayleigh and R index for LAr

### PR DESCRIPTION
**Pull request by lpaulucc**

### CODE REVIEW

**Comment by lgarren** [comment]
@lpaulucc  Would you give us a little more information about why these numbers need to be updated?   Thanks

**Comment by lgarren** [comment]
trigger build

**Comment by lpaulucc** [comment]
Dear Lynn,

The values for Rayleigh scattering and refractive index for LAr have being
recently measured with greater precision. There is growing evidence that
points to a value of around 90-100 cm for scattering at 128 nm instead of
the ~60 cm currently in lardataalg. Those values influence quite a lot the
outcome for the light that is going to be recorded by the photon detectors
in the experiments. Alex Himmel suggested that updating this in Larsoft
instead of only in dunetpc could be of interest among all experiments that
base their codes on Larsoft. The updated measures are consistent with the
ones presented in arXiv:2002.09346.
If you have more questions, please let me know.

Best,
Laura


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qui., 26 de mar. de 2020 às 16:51, Lynn Garren <notifications@github.com>
escreveu:

**Comment by lgarren** [comment]
@lpaulucc 
Thank you very much for the explanation.  The LArSoft collaboration may need to approve this change.  For starters, I've asked Erica to review the PR, and I've triggered the CI builds.

**Comment by lpaulucc** [comment]
Great, Lynn. Thank you.

Best,
Laura


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qui., 26 de mar. de 2020 às 17:03, Lynn Garren <notifications@github.com>
escreveu:

**Comment by aihimmel** [comment]
Important to note for the CI tests -- this change will affect the creation of photon libraries and parameterizations in the future, but it won't affect any running simulation in LArSoft since we aren't changing the libraries or parameterizations. DUNE has actually had longer scattering lengths in our parameterizations for some time, and this commit would bring the current state of the code in line with the way the simulations have been running.

**Comment by lgarren** [comment]
"In the SBN PDS working group meetings we have already discussed the new measurements, and we believe updating the index of refraction and Rayleigh scattering spectra obtained with the constrains coming form the recent group velocity measurements is the right way to follow. We are also planning to update soon our optical-libraries and semi-analytic corrections for the light simulation accordingly."

**Comment by lgarren** [comment]
approve

**Pull request merged**
