### PR TITLE
DetectorClocks documentation (Redmine issue #24928)

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
[Redmine issue: #24928](https://cdcvs.fnal.gov/redmine/issues/24928).

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by gartung** [comment]
trigger build

**Comment by gartung** [comment]
trigger build

**Comment by lgarren** [comment]
CI jobs:
c7: https://dbweb5.fnal.gov:8443/LarCI/app/view_builds/index?offset=0&builds=lar_ci/9490&builds=
e19: https://dbweb5.fnal.gov:8443/LarCI/app/view_builds/index?offset=0&builds=lar_ci/9491&builds=

**Comment by lgarren** [comment]
approve

**Pull request merged**
