### PR TITLE
Make modified box recombination parameters configurable

### PR DESCRIPTION
**Pull request by gputnam**

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by tomjunk** [comment]
Two comments:

"model" is misspelled as "moddel" in two places, and

I couldn't find where ModBoxA and ModBoxB are defined in fcl files.  There should be a default configuration fcl that people use even if they make no changes to their workflows with values that match the values in PhysicalConstants.h.  Maybe I didn't look in enough places?

**Comment by tomjunk** [comment]
Never mind my second comment -- they are defined in simulationservices.fcl, in the block standard_largeantparameters, as well as in PhysicalConstants.h.  In fact, it would be good to chase down any instances of using the one in PhysicalConstants.h as parameters that are defined in two places may eventually disagree.  We may want to study what happens if we assume different values in sim and reco to evaluate systematics, but this can be accomplished better with fcl than with header files.

**Comment by knoepfel** [comment]
@gputnam, are you able to address the misspellings that Tom mentions above:

https://github.com/LArSoft/lardataalg/pull/35#issuecomment-1217135696

**Comment by gputnam** [comment]
Will do @knoepfel! Sorry about the typo @tomjunk  -- thank you for catching it! The previous commit should fix the typo.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@tomjunk do you approve?

**Comment by tomjunk** [comment]
Approved

Thanks for fixing the typos!

**Comment by lgarren** [comment]
approve

**Pull request merged**
